name: Deploy to Surge

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: |
          surge ./src https://julio-mejia.surge.sh --token ${{ secrets.SURGE_TOKEN }}